// Date: 2015/10/17 12:00:10
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.BioStace.AutoTransfer.Model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelTransCart extends ModelBase
{
  //fields
    ModelRenderer CartRight;
    ModelRenderer CartLeft;
    ModelRenderer CartBack;
    ModelRenderer CartFront;
    ModelRenderer CartBottom;
  
  public ModelTransCart()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      CartRight = new ModelRenderer(this, 0, 0);
      CartRight.addBox(0F, 0F, 0F, 2, 8, 16);
      CartRight.setRotationPoint(-6F, 14F, -8F);
      CartRight.setTextureSize(64, 32);
      CartRight.mirror = true;
      setRotation(CartRight, 0F, 0F, 0F);
      CartLeft = new ModelRenderer(this, 0, 0);
      CartLeft.addBox(0F, 0F, 0F, 2, 8, 16);
      CartLeft.setRotationPoint(6F, 14F, 8F);
      CartLeft.setTextureSize(64, 32);
      CartLeft.mirror = true;
      setRotation(CartLeft, 0F, 3.173009F, 0F);
      CartBack = new ModelRenderer(this, 36, 0);
      CartBack.addBox(0F, 0F, 0F, 8, 8, 2);
      CartBack.setRotationPoint(-4F, 14F, -8F);
      CartBack.setTextureSize(64, 32);
      CartBack.mirror = true;
      setRotation(CartBack, 0F, 0F, 0F);
      CartFront = new ModelRenderer(this, 36, 0);
      CartFront.addBox(0F, 0F, 0F, 8, 8, 2);
      CartFront.setRotationPoint(4F, 14F, 8F);
      CartFront.setTextureSize(64, 32);
      CartFront.mirror = true;
      setRotation(CartFront, 0F, 3.141593F, 0F);
      CartBottom = new ModelRenderer(this, 36, 10);
      CartBottom.addBox(0F, 0F, 0F, 8, 1, 4);
      CartBottom.setRotationPoint(-4F, 21F, -2F);
      CartBottom.setTextureSize(64, 32);
      CartBottom.mirror = true;
      setRotation(CartBottom, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5,entity);
    CartRight.render(f5);
    CartLeft.render(f5);
    CartBack.render(f5);
    CartFront.render(f5);
    CartBottom.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
